# Generated by Django 4.2.7 on 2023-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_images_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='myImage/'),
        ),
    ]
